// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

$(function() {
  var Item, List, ListView, list_view, _ref, _ref1, _ref2;
  Item = (function(_super) {
    __extends(Item, _super);

    function Item() {
      _ref = Item.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Item.prototype.defaults = {
      part1: 'Hello',
      part2: 'Backbone'
    };

    return Item;

  })(Backbone.Model);
  List = (function(_super) {
    __extends(List, _super);

    function List() {
      _ref1 = List.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    List.prototype.model = Item;

    return List;

  })(Backbone.Collection);
  ListView = (function(_super) {
    __extends(ListView, _super);

    function ListView() {
      _ref2 = ListView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    ListView.prototype.el = $('body');

    ListView.prototype.initialize = function() {
      _.bindAll(this, 'render');
      this.coll = new List;
      this.coll.bind('add', this.appendItem);
      this.counter = 0;
      return this.render();
    };

    ListView.prototype.render = function() {
      this.$el.append('<button>Add</button>');
      return this.$el.append('<ul></ul>');
    };

    ListView.prototype.addItem = function() {
      var item;
      item = new Item;
      item.set('part2', "" + (item.get('part2')) + " " + (this.counter++));
      return this.coll.add(item);
    };

    ListView.prototype.appendItem = function(item) {
      return $('ul').append("<li>" + (item.get('part1')) + " " + (item.get('part2')) + "!</li>");
    };

    ListView.prototype.events = {
      'click button': 'addItem'
    };

    return ListView;

  })(Backbone.View);
  return list_view = new ListView;
});
