// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    console.log('/');
    return res.sendfile('public/wine.html');
  });

  app.get('/api/wines', function(req, res) {
    console.log('api/wines');
    return res.json([
      {
        id: '0',
        name: 'a'
      }, {
        id: '1',
        name: 'b'
      }
    ]);
  });

  app.use(express["static"]("" + __dirname + "/public"));

  app.listen('3333');

  console.log('listening on 3333');

}).call(this);
