// Generated by CoffeeScript 1.6.3
(function() {
  var DB, Dispatcher, Feeling, Session, User, UserFeelings, WaitItem, app, auto_feeling, clone, concat, express, gDB, gDispatcher, len, max, merge_feelings, min, now, rand, remove_item, require_auth, schedule, u0, u1, u2, valid_session;

  express = require('express');

  app = express();

  valid_session = function(user_id) {
    var ss;
    if (!user_id) {
      return false;
    }
    ss = gDB.session(user_id);
    if (!ss) {
      return false;
    }
    if (ss.expired()) {
      gDB.del_session(user_id);
      return false;
    }
    ss.update();
    return true;
  };

  require_auth = function(req, res, next) {
    var me;
    if (!valid_session(req.session.user_id)) {
      console.log('401');
      return res.send(401);
    } else {
      me = gDB.user(req.session.user_id);
      return next();
    }
  };

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.cookieParser());
    app.use(express.cookieSession({
      secret: 'deadbeef'
    }));
    app.use(express.logger({
      format: ':method :url'
    }));
    app.use(function(err, req, res, next) {
      console.error(err.stack);
      return res.send(500, 'Something broke!');
    });
    app.use(app.router);
    app.all('/api/*', require_auth);
    return app.use(express["static"]("" + __dirname + "/public"));
  });

  app.get('/', function(req, res) {
    return res.sendfile('public/index.html');
  });

  app.get('/sessions', function(req, res) {
    if (!valid_session(req.session.user_id)) {
      return res.send(401);
    } else {
      return res.json({
        user_id: req.session.user_id
      });
    }
  });

  app.post('/sessions', function(req, res) {
    var u, user_id;
    if (valid_session(req.session.user_id)) {
      res.send(400, "Need to logout");
      return;
    }
    user_id = gDB.email(req.body.email);
    if (user_id) {
      u = gDB.user(user_id);
      if (u && u.password === req.body.password) {
        req.session.user_id = u.id;
        Session.create(u.id);
        res.json({});
        return;
      }
    }
    return res.send(404, "Invalid email or password");
  });

  app.del('/sessions', function(req, res) {
    if (!valid_session(req.session.user_id)) {
      return res.send(401);
    } else {
      gDB.del_session(req.session.user_id);
      return res.json({});
    }
  });

  DB = (function() {
    DB.prototype.feelings_seq = 1;

    DB.prototype.users_seq = 1;

    function DB() {
      this._sessions = {};
      this._emails = {};
      this._users = {};
      this._feelings = {};
    }

    DB.prototype.session = function(id) {
      return this._sessions[id];
    };

    DB.prototype.put_session = function(id, data) {
      return this._sessions[id] = data;
    };

    DB.prototype.del_session = function(id) {
      return delete this._sessions[id];
    };

    DB.prototype.email = function(email) {
      return this._emails[email];
    };

    DB.prototype.put_email = function(user) {
      return this._emails[user.email] = user.id;
    };

    DB.prototype.del_email = function(email) {
      return delete this._emails[email];
    };

    DB.prototype.users = function() {
      return this._users;
    };

    DB.prototype.user = function(id) {
      return this._users[id];
    };

    DB.prototype.put_user = function(user) {
      return this._users[user.id] = user;
    };

    DB.prototype.del_user = function(id) {
      return delete this._users[id];
    };

    DB.prototype.feelings = function() {
      return this._feelings;
    };

    DB.prototype.feeling = function(id) {
      return this._feelings[id];
    };

    DB.prototype.put_feeling = function(feeling) {
      return this._feelings[feeling.id] = feeling;
    };

    DB.prototype.del_feeling = function(id) {
      return delete this._feelings[id];
    };

    return DB;

  })();

  Session = (function() {
    Session.EXPIRE_TIME = 60 * 1000;

    Session.create = function(uid) {
      var s;
      s = new Session(uid);
      gDB.put_session(uid, s);
      return s;
    };

    function Session(user_id) {
      this.user_id = user_id;
      this.update();
    }

    Session.prototype.update = function() {
      return this.time = now();
    };

    Session.prototype.expired = function() {
      return now() - this.time > Session.EXPIRE_TIME;
    };

    return Session;

  })();

  Feeling = (function() {
    Feeling.SHARE_DUR = 60 * 60 * 1000;

    Feeling.DETACHABLE_DUR = Feeling.SHARE_DUR / 2;

    Feeling.create = function(me, is_public, word, blah) {
      var f;
      f = new Feeling(me, is_public, word, blah);
      gDB.put_feeling(f);
      me.feelings.push_mine(f.id);
      if (is_public) {
        gDispatcher.register_item(f.id);
      }
      return f;
    };

    function Feeling(me, is_public, word, blah) {
      this.word = word;
      this.blah = blah;
      this.user_id = me.id;
      this.id = gDB.feelings_seq++;
      this.status = is_public ? 'public' : 'private';
      this.time = now();
      this.talks = {};
    }

    Feeling.prototype.sharable_time = function() {
      return now() - this.time < Feeling.SHARE_DUR;
    };

    Feeling.prototype.sharable = function() {
      return this.status === 'public' && this.sharable_time();
    };

    Feeling.prototype.has_own_perm = function(user_id) {
      return this.user_id === user_id;
    };

    Feeling.prototype.has_group_perm = function(user_id) {
      return this.has_own_perm(user_id) || this.talks[user_id];
    };

    Feeling.prototype.grant_group_perm = function(uid) {
      return this.talks[uid] = [];
    };

    Feeling.prototype.summary = function() {
      return {
        id: this.id,
        user_id: this.user_id,
        time: this.time,
        word: this.word
      };
    };

    Feeling.prototype.extend = function(user_id) {
      var comments, tuid, u, x, _ref;
      x = clone(this);
      u = gDB.user(x.user_id);
      x.user = u.summary();
      x.share = this.sharable();
      if (!this.has_own_perm(user_id)) {
        x.own = false;
        x.n_talk_users = 1;
        console.log(JSON.stringify(this));
        x.n_talk_msgs = this.talks[user_id].length;
      } else {
        x.own = true;
        x.n_talk_users = len(x.talks);
        x.n_talk_msgs = 0;
        _ref = x.talks;
        for (tuid in _ref) {
          comments = _ref[tuid];
          x.n_talk_msgs += this.talks[tuid].length;
        }
      }
      return x;
    };

    Feeling.prototype.extend_full = function(user_id) {
      var comments, tu, tuid, u, x, _ref;
      x = this.extend(user_id);
      if (!this.has_own_perm(user_id)) {
        x.talks[user_id] = this.talks[user_id];
      }
      u = gDB.user(user_id);
      x.talk_user = {};
      x.talk_user[u.id] = {
        name: u.name,
        img: u.img
      };
      _ref = x.talks;
      for (tuid in _ref) {
        comments = _ref[tuid];
        tu = gDB.user(tuid);
        x.talk_user[tuid] = {
          name: tu.name,
          img: tu.img
        };
      }
      return x;
    };

    Feeling.prototype.weight = function(wait_time) {
      return 0;
    };

    Feeling.prototype.set_public = function(is_public) {
      if (this.status === 'removed') {
        return;
      }
      if (this.status === 'private' && is_public) {
        this.status = 'public';
        if (this.sharable()) {
          return gDispatcher.register_item(this.id);
        }
      } else if (this.status === 'public' && !is_public) {
        return this.status = 'private';
      }
    };

    Feeling.prototype.remove = function() {
      this.status = 'removed';
      this.blah = '';
      return this.talks = {};
    };

    return Feeling;

  })();

  UserFeelings = (function() {
    function UserFeelings() {
      this._actives = [];
      this._mines = [];
      this._rcvs = [];
    }

    UserFeelings.prototype.push_mine = function(id) {
      this._actives.push(id);
      return this._mines.unshift(id);
    };

    UserFeelings.prototype.push_rcv = function(id) {
      this._actives.push(id);
      return this._rcvs.unshift(id);
    };

    UserFeelings.prototype.mine_len = function() {
      return this._mines.length;
    };

    UserFeelings.prototype.rcvs_len = function() {
      return this._rcvs.length;
    };

    UserFeelings.prototype.total_len = function() {
      return this._mines.length + this._rcvs.length;
    };

    UserFeelings.prototype.my_actives = function(uid) {
      var f, r, _i, _len, _ref;
      r = [];
      _ref = this.actives();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        if (f.has_own_perm(uid)) {
          r.push;
        }
      }
      return r;
    };

    UserFeelings.prototype.rcv_actives = function(uid) {
      var f, r, _i, _len, _ref;
      r = [];
      _ref = this.actives();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        if (!f.has_own_perm(uid)) {
          r.push;
        }
      }
      return r;
    };

    UserFeelings.prototype.actives = function() {
      return this._filter_actives().map(function(fid) {
        return gDB.feeling(fid);
      });
    };

    UserFeelings.prototype._filter_actives = function() {
      var f, fid, _i, _len, _now, _ref;
      _now = now();
      _ref = this._actives;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fid = _ref[_i];
        f = gDB.feeling(fid);
        if (f && _now - f.time < Feeling.SHARE_DUR + Feeling.DETACHABLE_DUR) {
          break;
        }
        this.actives.unshift();
      }
      return this._actives;
    };

    UserFeelings.prototype.mine = function(s, e) {
      return this._mine.slice(s, e).map(function(fid) {
        return gDB.feeling(fid);
      });
    };

    UserFeelings.prototype.rcvs = function(s, e) {
      return this._rcvs.slice(s, e).map(function(fid) {
        return gDB.feeling(fid);
      });
    };

    return UserFeelings;

  })();

  User = (function() {
    User.create = function(name, img, email, password) {
      var u;
      u = new User(name, img, email, password);
      gDB.put_user(u);
      gDB.put_email(u);
      gDispatcher.register_user(u.id);
      return u;
    };

    function User(name, img, email, password) {
      this.name = name;
      this.img = img;
      this.email = email;
      this.password = password;
      this.id = gDB.users_seq++;
      this.n_hearts = 0;
      this.n_availables = 0;
      this.arrived_feelings = [];
      this.feelings = new UserFeelings();
    }

    User.prototype.summary = function(extend) {
      var u;
      if (extend == null) {
        extend = false;
      }
      u = clone(this);
      delete u.password;
      u.arrived_feelings = this.arrived_feelings.length;
      u.my_feelings = this.feelings.mine_len();
      u.rcv_feelings = this.feelings.rcvs_len();
      if (extend) {
        u.my_shared = this.feelings.my_actives().length;
        u.rcv_shared = this.feelings.rcv_actives().length;
      }
      return u;
    };

    User.prototype.valid_arrived_feeling = function(id) {
      return this.arrived_feelings.length > 0 && ("" + this.arrived_feelings[0]) === id;
    };

    User.prototype.pop_arrived_feeling = function() {
      var fid;
      fid = this.arrived_feelings.pop();
      this.arrived_feelings = [];
      return gDispatcher.register_user(this.id);
    };

    User.prototype.grab_feeling = function(fid) {
      return this.feelings.push_rcv(fid);
    };

    return User;

  })();

  WaitItem = (function() {
    function WaitItem(id) {
      this.id = id;
      this.wait_time = now();
    }

    return WaitItem;

  })();

  Dispatcher = (function() {
    Dispatcher.MIN_USER_WAIT_TIME = 5000;

    Dispatcher.INTERVAL = 5000;

    function Dispatcher() {
      var u, uid, _ref;
      this._user_que = [];
      this._item_que = [];
      _ref = gDB.users();
      for (uid in _ref) {
        u = _ref[uid];
        if (u.arrived_feelings.length === 0) {
          register_user(uid);
        }
      }
      this._user_que.sort(function(a, b) {
        return a.wait_time - b.wait_time;
      });
    }

    Dispatcher.prototype.run = function() {
      var fid, hungry_users, u, wu, _now, _results;
      hungry_users = [];
      _now = now();
      while (this._user_que.length > 0) {
        wu = this._user_que.shift();
        u = gDB.user(wu.id);
        if (!u) {
          continue;
        }
        if (_now - u.wait_time < Dispatcher.MIN_USER_WAIT_TIME) {
          hungry_users.push(wu);
          break;
        }
        fid = this.select_item(wu);
        if (!fid) {
          hungry_users.push(wu);
          continue;
        }
        u.arrived_feelings.push(fid);
      }
      _results = [];
      while (hungry_users.length > 0) {
        _results.push(this._user_que.unshift(hungry_users.pop()));
      }
      return _results;
    };

    Dispatcher.prototype.select_item = function(wu) {
      var candidates, f, item, n, n_candi, reusable, selected, wf, _i, _ref;
      candidates = [];
      n_candi = 0;
      reusable = [];
      while (this._item_que.length > 0 && n_candi < 30) {
        wf = this._item_que.shift();
        item = gDB.feeling(wf.id);
        if (!(item && item.sharable())) {
          continue;
        }
        reusable.push(wf);
        if (item.has_group_perm(wu.id)) {
          continue;
        }
        for (n = _i = 0, _ref = item.weight(wu.wait_time); 0 <= _ref ? _i <= _ref : _i >= _ref; n = 0 <= _ref ? ++_i : --_i) {
          candidates.push(wf);
        }
        n_candi++;
      }
      selected = candidates.length === 0 ? null : candidates[rand(0, candidates.length - 1)];
      while (reusable.length > 0) {
        f = reusable.shift();
        if (selected && selected.id === f.id) {
          continue;
        }
        this._item_que.push(f);
      }
      if (selected) {
        this._item_que.push(selected);
      }
      return selected != null ? selected.id : void 0;
    };

    Dispatcher.prototype.register_item = function(id) {
      return this._item_que.push(new WaitItem(id));
    };

    Dispatcher.prototype.register_user = function(uid) {
      return this._user_que.push(new WaitItem(uid));
    };

    Dispatcher.prototype.log = function() {
      var items, u, uid, users, wf, wu, _i, _j, _len, _len1, _ref, _ref1, _ref2;
      console.log("name, hearts, arrived, my, rcv");
      _ref = gDB.users();
      for (uid in _ref) {
        u = _ref[uid];
        console.log("" + u.name + ", " + u.n_hearts + ", " + u.arrived_feelings.length + ", " + (u.feelings.mine_len()) + ", " + (u.feelings.rcvs_len()));
      }
      users = [];
      _ref1 = this._user_que;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        wu = _ref1[_i];
        users.push(JSON.stringify(gDB.user(wu.id).name));
      }
      console.log("userQ: " + (users.join()));
      items = [];
      _ref2 = this._item_que;
      for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
        wf = _ref2[_j];
        items.push(wf.id);
      }
      return console.log("itemQ: " + (items.join()));
    };

    return Dispatcher;

  })();

  app.post('/users', function(req, res) {
    var email, name, password;
    name = req.body.name;
    email = req.body.email;
    password = req.body.password;
    if (gDB.email(email)) {
      res.send(400, "Duplicated email");
      return;
    }
    User.create(name, 'img/profile.jpg', email, password);
    return res.json({});
  });

  app.get('/api/me', function(req, res) {
    var me;
    me = gDB.user(req.session.user_id);
    return res.json(me.summary(true));
  });

  app.get('/api/feelings', function(req, res) {
    var me, n, skip, type;
    me = gDB.user(req.session.user_id);
    skip = req.params.skip || 0;
    n = req.params.n || 30;
    type = req.params.type;
    return res.json(type === 'my' ? me.feelings.mine(max(0, skip), min(me.feelings.mine_len(), skip + n)).map(function(f) {
      return f.extend(me.id);
    }) : type === 'rcv' ? me.feelings.rcvs(max(0, skip), min(me.feelings.rcvs_len(), skip + n)).map(function(f) {
      return f.extend(me.id);
    }) : me.feelings.actives().map(function(f) {
      return f.extend(me.id);
    }));
  });

  app.post('/api/feelings', function(req, res) {
    var blah, is_public, me, word;
    me = gDB.user(req.session.user_id);
    word = req.body.word;
    blah = req.body.blah;
    is_public = req.body.is_public || true;
    if (!(word && blah && is_public)) {
      res.send(400, "Invalid Parameters");
      return;
    }
    Feeling.create(me, is_public, word, blah);
    return res.json({});
  });

  app.get('/api/feelings/:id', function(req, res) {
    var f, id, me;
    me = gDB.user(req.session.user_id);
    id = req.params.id;
    f = gDB.feeling(id);
    if (!f) {
      return res.send(404, "No such feeling: " + id);
    } else if (!f.has_group_perm(me.id)) {
      return res.json(f.summary());
    } else {
      return res.json(f.extend_full(me.id));
    }
  });

  app.put('/api/feelings/:id', function(req, res) {
    var f, id, is_public, me;
    me = gDB.user(req.session.user_id);
    id = req.params.id;
    is_public = req.body.is_public;
    f = gDB.feeling(id);
    if (!(f && f.has_own_perm(me.id))) {
      return res.send(406, "No permission to access this feeling: " + id);
    } else {
      f.set_public(is_public);
      return res.json({});
    }
  });

  app.put('/api/feelings/:id/like', function(req, res) {
    var f, id, me, user_id;
    me = gDB.user(req.session.user_id);
    id = req.params.id;
    user_id = req.body.user_id;
    f = gDB.feeling(id);
    if (!(f && f.has_own_perm(me.id))) {
      return res.send(406, "No permission to access this feeling: " + id);
    } else {
      if (f.like) {
        return res.send(406, "Already Done");
      } else {
        f.like = user_id;
        gDB.user(user_id).n_hearts++;
        return res.json({});
      }
    }
  });

  app.del('/api/feelings/:id', function(req, res) {
    var f, id, me;
    me = gDB.user(req.session.user_id);
    id = req.params.id;
    f = gDB.feeling(id);
    if (!(f && f.has_own_perm(me.id))) {
      return res.send(406, "No permission to access this feeling: " + id);
    } else {
      f.remove();
      return res.json({});
    }
  });

  app.post('/api/feelings/:id/talks/:user_id/comments', function(req, res) {
    var blah, f, id, me, user_id;
    me = gDB.user(req.session.user_id);
    id = req.params.id;
    user_id = req.params.user_id;
    blah = req.body.blah;
    f = gDB.feeling(id);
    if (!(f && f.has_group_perm(me.id))) {
      res.send(406, "No permission to access this feeling: " + id);
      return;
    }
    if (!f.sharable()) {
      res.send(406, "This feeling is no longer sharable.");
      return;
    }
    if (f.has_own_perm(me.id)) {
      f.talks[user_id].push({
        user_id: user_id,
        blah: blah,
        time: now()
      });
    } else {
      f.talks[me.id].push({
        user_id: me.id,
        blah: blah,
        time: now()
      });
    }
    return res.json({});
  });

  app.get('/api/arrived_feelings', function(req, res) {
    var f, fid, me, r, _i, _len, _ref;
    me = gDB.user(req.session.user_id);
    r = [];
    _ref = me.arrived_feelings;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      fid = _ref[_i];
      f = gDB.feeling(fid);
      if (f && f.sharable()) {
        r.push(f.summary());
      }
    }
    return res.json(r);
  });

  app.put('/api/arrived_feelings/:id', function(req, res) {
    var f, id, me;
    me = gDB.user(req.session.user_id);
    id = req.params.id;
    if (!me.valid_arrived_feeling(id)) {
      res.send(404, "No such feeling: " + id);
      return;
    }
    me.pop_arrived_feeling();
    f = gDB.feeling(id);
    if (!(f && f.sharable())) {
      throw "This feeling is no longer sharable.";
    }
    f.grant_group_perm(me.id);
    me.grab_feeling(id);
    return res.json(f.extend_full(me.id));
  });

  clone = function(obj) {
    return JSON.parse(JSON.stringify(obj));
  };

  max = function(a, b) {
    if (a >= b) {
      return a;
    } else {
      return b;
    }
  };

  min = function(a, b) {
    if (a < b) {
      return a;
    } else {
      return b;
    }
  };

  remove_item = function(arr, i) {
    if (i > -1) {
      return arr.splice(i, 1);
    }
  };

  now = function() {
    return new Date().getTime();
  };

  rand = function(s, e) {
    return Math.round(Math.random() * e) + s;
  };

  concat = function(a, b) {
    var x, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = b.length; _i < _len; _i++) {
      x = b[_i];
      _results.push(a.push(x));
    }
    return _results;
  };

  len = function(obj) {
    return Object.keys(obj).length;
  };

  merge_feelings = function(a, b) {
    var af, bf, i, j, r;
    r = [];
    i = j = 0;
    while (true) {
      if (a.length === i) {
        concat(r, b.slice(j, b.length));
        return r;
      }
      if (b.length === j) {
        concat(r, a.slice(i, a.length));
        return r;
      }
      af = gDB.feeling(a[i]);
      bf = gDB.feeling(b[j]);
      if (af.time > bf.time) {
        r.push(af);
        i++;
      } else {
        r.push(bf);
        j++;
      }
    }
    return r;
  };

  gDB = new DB();

  gDispatcher = new Dispatcher();

  schedule = function() {
    gDispatcher.run();
    gDispatcher.log();
    return setTimeout(schedule, Dispatcher.INTERVAL);
  };

  schedule();

  u0 = User.create('sun', 'img/profile.jpg', 'sun@gmail.com', 'sun00');

  u1 = User.create('moon', 'img/profile.jpg', 'moon@gmail.com', 'moon00');

  u2 = User.create('asdf', 'img/profile.jpg', 'asdf', 'asdf');

  auto_feeling = function() {
    var a, n, word, _i, _ref;
    console.log('## auto fill started');
    word = rand(0, 29);
    a = [];
    for (n = _i = 0, _ref = rand(0, 9); 0 <= _ref ? _i <= _ref : _i >= _ref; n = 0 <= _ref ? ++_i : --_i) {
      a.push('blah');
    }
    Feeling.create(u0, true, word, a.join(''));
    setTimeout(auto_feeling, 10000);
    return console.log('## auto fill done');
  };

  auto_feeling();

  app.listen('3333');

  console.log('listening on 3333');

}).call(this);
